# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled_2.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(650, 384)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(1200, 1000))
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMaximumSize(QtCore.QSize(2000, 2000))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.mainGrid = QtGui.QGridLayout()
        self.mainGrid.setObjectName(_fromUtf8("mainGrid"))
        self.line_13 = QtGui.QFrame(self.centralwidget)
        self.line_13.setFrameShadow(QtGui.QFrame.Plain)
        self.line_13.setLineWidth(2)
        self.line_13.setFrameShape(QtGui.QFrame.VLine)
        self.line_13.setObjectName(_fromUtf8("line_13"))
        self.mainGrid.addWidget(self.line_13, 1, 1, 3, 1)
        self.gridLayout_Box1_4 = QtGui.QGridLayout()
        self.gridLayout_Box1_4.setSpacing(6)
        self.gridLayout_Box1_4.setObjectName(_fromUtf8("gridLayout_Box1_4"))
        self.birdEntry_Box1_4 = QtGui.QPlainTextEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.birdEntry_Box1_4.sizePolicy().hasHeightForWidth())
        self.birdEntry_Box1_4.setSizePolicy(sizePolicy)
        self.birdEntry_Box1_4.setMaximumSize(QtCore.QSize(200, 26))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.birdEntry_Box1_4.setFont(font)
        self.birdEntry_Box1_4.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.birdEntry_Box1_4.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.birdEntry_Box1_4.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.birdEntry_Box1_4.setPlainText(_fromUtf8(""))
        self.birdEntry_Box1_4.setProperty("HAlign", _fromUtf8(""))
        self.birdEntry_Box1_4.setObjectName(_fromUtf8("birdEntry_Box1_4"))
        self.gridLayout_Box1_4.addWidget(self.birdEntry_Box1_4, 8, 1, 1, 2)
        spacerItem = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_Box1_4.addItem(spacerItem, 6, 0, 1, 1)
        self.checkActive_Box1_4 = QtGui.QCheckBox(self.centralwidget)
        self.checkActive_Box1_4.setMaximumSize(QtCore.QSize(22, 22))
        self.checkActive_Box1_4.setText(_fromUtf8(""))
        self.checkActive_Box1_4.setIconSize(QtCore.QSize(20, 20))
        self.checkActive_Box1_4.setProperty("HAlign", _fromUtf8(""))
        self.checkActive_Box1_4.setObjectName(_fromUtf8("checkActive_Box1_4"))
        self.gridLayout_Box1_4.addWidget(self.checkActive_Box1_4, 4, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_Box1_4 = QtGui.QLabel(self.centralwidget)
        self.label_Box1_4.setObjectName(_fromUtf8("label_Box1_4"))
        self.gridLayout_Box1_4.addWidget(self.label_Box1_4, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        spacerItem1 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_Box1_4.addItem(spacerItem1, 3, 0, 1, 1)
        self.birdEntryLabel_Box1_4 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.birdEntryLabel_Box1_4.sizePolicy().hasHeightForWidth())
        self.birdEntryLabel_Box1_4.setSizePolicy(sizePolicy)
        self.birdEntryLabel_Box1_4.setMaximumSize(QtCore.QSize(500, 26))
        self.birdEntryLabel_Box1_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.birdEntryLabel_Box1_4.setObjectName(_fromUtf8("birdEntryLabel_Box1_4"))
        self.gridLayout_Box1_4.addWidget(self.birdEntryLabel_Box1_4, 8, 0, 1, 1)
        self.paramFileButton_Box1_4 = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.paramFileButton_Box1_4.sizePolicy().hasHeightForWidth())
        self.paramFileButton_Box1_4.setSizePolicy(sizePolicy)
        self.paramFileButton_Box1_4.setMaximumSize(QtCore.QSize(26, 26))
        self.paramFileButton_Box1_4.setProperty("HAlign", _fromUtf8(""))
        self.paramFileButton_Box1_4.setObjectName(_fromUtf8("paramFileButton_Box1_4"))
        self.gridLayout_Box1_4.addWidget(self.paramFileButton_Box1_4, 7, 3, 1, 1)
        self.checkActiveLabel_Box1_4 = QtGui.QLabel(self.centralwidget)
        self.checkActiveLabel_Box1_4.setAlignment(QtCore.Qt.AlignCenter)
        self.checkActiveLabel_Box1_4.setProperty("HAlign", _fromUtf8(""))
        self.checkActiveLabel_Box1_4.setObjectName(_fromUtf8("checkActiveLabel_Box1_4"))
        self.gridLayout_Box1_4.addWidget(self.checkActiveLabel_Box1_4, 5, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.paramFileLabel_Box1_4 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.paramFileLabel_Box1_4.sizePolicy().hasHeightForWidth())
        self.paramFileLabel_Box1_4.setSizePolicy(sizePolicy)
        self.paramFileLabel_Box1_4.setMaximumSize(QtCore.QSize(500, 26))
        self.paramFileLabel_Box1_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.paramFileLabel_Box1_4.setObjectName(_fromUtf8("paramFileLabel_Box1_4"))
        self.gridLayout_Box1_4.addWidget(self.paramFileLabel_Box1_4, 7, 0, 1, 1)
        self.paramFile_Box1_4 = QtGui.QTextEdit(self.centralwidget)
        self.paramFile_Box1_4.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.paramFile_Box1_4.sizePolicy().hasHeightForWidth())
        self.paramFile_Box1_4.setSizePolicy(sizePolicy)
        self.paramFile_Box1_4.setMaximumSize(QtCore.QSize(200, 26))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.paramFile_Box1_4.setFont(font)
        self.paramFile_Box1_4.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.paramFile_Box1_4.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.paramFile_Box1_4.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.paramFile_Box1_4.setProperty("HAlign", _fromUtf8(""))
        self.paramFile_Box1_4.setObjectName(_fromUtf8("paramFile_Box1_4"))
        self.gridLayout_Box1_4.addWidget(self.paramFile_Box1_4, 7, 1, 1, 2)
        spacerItem2 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_Box1_4.addItem(spacerItem2, 1, 0, 1, 1)
        self.stop_Box1_4 = QtGui.QPushButton(self.centralwidget)
        self.stop_Box1_4.setMaximumSize(QtCore.QSize(100, 16777215))
        self.stop_Box1_4.setProperty("HAlign", _fromUtf8(""))
        self.stop_Box1_4.setObjectName(_fromUtf8("stop_Box1_4"))
        self.gridLayout_Box1_4.addWidget(self.stop_Box1_4, 9, 1, 1, 1)
        self.start_Box1_4 = QtGui.QPushButton(self.centralwidget)
        self.start_Box1_4.setMaximumSize(QtCore.QSize(100, 16777215))
        self.start_Box1_4.setProperty("HAlign", _fromUtf8(""))
        self.start_Box1_4.setObjectName(_fromUtf8("start_Box1_4"))
        self.gridLayout_Box1_4.addWidget(self.start_Box1_4, 9, 2, 1, 1)
        self.graphic_Box1_4 = QtGui.QGraphicsView(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphic_Box1_4.sizePolicy().hasHeightForWidth())
        self.graphic_Box1_4.setSizePolicy(sizePolicy)
        self.graphic_Box1_4.setMaximumSize(QtCore.QSize(35, 35))
        self.graphic_Box1_4.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphic_Box1_4.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphic_Box1_4.setInteractive(False)
        self.graphic_Box1_4.setProperty("HAlign", _fromUtf8(""))
        self.graphic_Box1_4.setObjectName(_fromUtf8("graphic_Box1_4"))
        self.gridLayout_Box1_4.addWidget(self.graphic_Box1_4, 2, 0, 1, 1)
        self.statusText_Box1_4 = QtGui.QTextBrowser(self.centralwidget)
        self.statusText_Box1_4.setMaximumSize(QtCore.QSize(230, 180))
        self.statusText_Box1_4.setProperty("HAlign", _fromUtf8(""))
        self.statusText_Box1_4.setObjectName(_fromUtf8("statusText_Box1_4"))
        self.gridLayout_Box1_4.addWidget(self.statusText_Box1_4, 0, 1, 7, 2)
        self.mainGrid.addLayout(self.gridLayout_Box1_4, 1, 2, 1, 1)
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.mainGrid.addWidget(self.line_2, 2, 0, 1, 1)
        self.line_7 = QtGui.QFrame(self.centralwidget)
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.mainGrid.addWidget(self.line_7, 2, 2, 1, 1)
        self.gridLayout_Box1 = QtGui.QGridLayout()
        self.gridLayout_Box1.setSpacing(6)
        self.gridLayout_Box1.setObjectName(_fromUtf8("gridLayout_Box1"))
        self.birdEntryLabel_Box1 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.birdEntryLabel_Box1.sizePolicy().hasHeightForWidth())
        self.birdEntryLabel_Box1.setSizePolicy(sizePolicy)
        self.birdEntryLabel_Box1.setMaximumSize(QtCore.QSize(500, 26))
        self.birdEntryLabel_Box1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.birdEntryLabel_Box1.setObjectName(_fromUtf8("birdEntryLabel_Box1"))
        self.gridLayout_Box1.addWidget(self.birdEntryLabel_Box1, 8, 0, 1, 1)
        self.label_Box1 = QtGui.QLabel(self.centralwidget)
        self.label_Box1.setObjectName(_fromUtf8("label_Box1"))
        self.gridLayout_Box1.addWidget(self.label_Box1, 0, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.checkActive_Box1 = QtGui.QCheckBox(self.centralwidget)
        self.checkActive_Box1.setMaximumSize(QtCore.QSize(22, 22))
        self.checkActive_Box1.setText(_fromUtf8(""))
        self.checkActive_Box1.setIconSize(QtCore.QSize(20, 20))
        self.checkActive_Box1.setProperty("HAlign", _fromUtf8(""))
        self.checkActive_Box1.setObjectName(_fromUtf8("checkActive_Box1"))
        self.gridLayout_Box1.addWidget(self.checkActive_Box1, 4, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.checkActiveLabel_Box1 = QtGui.QLabel(self.centralwidget)
        self.checkActiveLabel_Box1.setAlignment(QtCore.Qt.AlignCenter)
        self.checkActiveLabel_Box1.setProperty("HAlign", _fromUtf8(""))
        self.checkActiveLabel_Box1.setObjectName(_fromUtf8("checkActiveLabel_Box1"))
        self.gridLayout_Box1.addWidget(self.checkActiveLabel_Box1, 5, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.paramFileLabel_Box1 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.paramFileLabel_Box1.sizePolicy().hasHeightForWidth())
        self.paramFileLabel_Box1.setSizePolicy(sizePolicy)
        self.paramFileLabel_Box1.setMaximumSize(QtCore.QSize(500, 26))
        self.paramFileLabel_Box1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.paramFileLabel_Box1.setObjectName(_fromUtf8("paramFileLabel_Box1"))
        self.gridLayout_Box1.addWidget(self.paramFileLabel_Box1, 7, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_Box1.addItem(spacerItem3, 1, 0, 1, 1)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setMaximumSize(QtCore.QSize(35, 35))
        self.label.setFrameShape(QtGui.QFrame.Panel)
        self.label.setFrameShadow(QtGui.QFrame.Sunken)
        self.label.setMidLineWidth(0)
        self.label.setText(_fromUtf8(""))
        self.label.setPixmap(QtGui.QPixmap(_fromUtf8(":/boxIcons/red_stop.svg")))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_Box1.addWidget(self.label, 2, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.statusText_Box1 = QtGui.QTextBrowser(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusText_Box1.sizePolicy().hasHeightForWidth())
        self.statusText_Box1.setSizePolicy(sizePolicy)
        self.statusText_Box1.setMinimumSize(QtCore.QSize(0, 215))
        self.statusText_Box1.setMaximumSize(QtCore.QSize(230, 215))
        self.statusText_Box1.setProperty("HAlign", _fromUtf8(""))
        self.statusText_Box1.setObjectName(_fromUtf8("statusText_Box1"))
        self.gridLayout_Box1.addWidget(self.statusText_Box1, 0, 1, 7, 3)
        self.paramFileButton_Box1 = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.paramFileButton_Box1.sizePolicy().hasHeightForWidth())
        self.paramFileButton_Box1.setSizePolicy(sizePolicy)
        self.paramFileButton_Box1.setMaximumSize(QtCore.QSize(26, 26))
        self.paramFileButton_Box1.setProperty("HAlign", _fromUtf8(""))
        self.paramFileButton_Box1.setObjectName(_fromUtf8("paramFileButton_Box1"))
        self.gridLayout_Box1.addWidget(self.paramFileButton_Box1, 7, 3, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_Box1.addItem(spacerItem4, 3, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_Box1.addItem(spacerItem5, 6, 0, 1, 1)
        self.birdEntry_Box1 = QtGui.QPlainTextEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.birdEntry_Box1.sizePolicy().hasHeightForWidth())
        self.birdEntry_Box1.setSizePolicy(sizePolicy)
        self.birdEntry_Box1.setMaximumSize(QtCore.QSize(200, 26))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.birdEntry_Box1.setFont(font)
        self.birdEntry_Box1.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.birdEntry_Box1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.birdEntry_Box1.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.birdEntry_Box1.setPlainText(_fromUtf8(""))
        self.birdEntry_Box1.setProperty("HAlign", _fromUtf8(""))
        self.birdEntry_Box1.setObjectName(_fromUtf8("birdEntry_Box1"))
        self.gridLayout_Box1.addWidget(self.birdEntry_Box1, 8, 1, 1, 2)
        self.paramFile_Box1 = QtGui.QTextEdit(self.centralwidget)
        self.paramFile_Box1.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.paramFile_Box1.sizePolicy().hasHeightForWidth())
        self.paramFile_Box1.setSizePolicy(sizePolicy)
        self.paramFile_Box1.setMaximumSize(QtCore.QSize(200, 26))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.paramFile_Box1.setFont(font)
        self.paramFile_Box1.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.paramFile_Box1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.paramFile_Box1.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.paramFile_Box1.setProperty("HAlign", _fromUtf8(""))
        self.paramFile_Box1.setObjectName(_fromUtf8("paramFile_Box1"))
        self.gridLayout_Box1.addWidget(self.paramFile_Box1, 7, 1, 1, 2)
        self.toolButton = QtGui.QToolButton(self.centralwidget)
        self.toolButton.setMinimumSize(QtCore.QSize(26, 26))
        self.toolButton.setMaximumSize(QtCore.QSize(56, 26))
        self.toolButton.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("icons/wrench.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon)
        self.toolButton.setPopupMode(QtGui.QToolButton.InstantPopup)
        self.toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolButton.setAutoRaise(True)
        self.toolButton.setArrowType(QtCore.Qt.NoArrow)
        self.toolButton.setObjectName(_fromUtf8("toolButton"))
        self.gridLayout_Box1.addWidget(self.toolButton, 10, 3, 1, 1)
        self.stop_Box1 = QtGui.QPushButton(self.centralwidget)
        self.stop_Box1.setMaximumSize(QtCore.QSize(100, 16777215))
        self.stop_Box1.setProperty("HAlign", _fromUtf8(""))
        self.stop_Box1.setObjectName(_fromUtf8("stop_Box1"))
        self.gridLayout_Box1.addWidget(self.stop_Box1, 10, 1, 1, 1)
        self.start_Box1 = QtGui.QPushButton(self.centralwidget)
        self.start_Box1.setMaximumSize(QtCore.QSize(100, 16777215))
        self.start_Box1.setProperty("HAlign", _fromUtf8(""))
        self.start_Box1.setObjectName(_fromUtf8("start_Box1"))
        self.gridLayout_Box1.addWidget(self.start_Box1, 10, 2, 1, 1)
        self.mainGrid.addLayout(self.gridLayout_Box1, 1, 0, 1, 1)
        self.menuGrid = QtGui.QGridLayout()
        self.menuGrid.setObjectName(_fromUtf8("menuGrid"))
        self.stopAllButton = QtGui.QPushButton(self.centralwidget)
        self.stopAllButton.setObjectName(_fromUtf8("stopAllButton"))
        self.menuGrid.addWidget(self.stopAllButton, 0, 0, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.menuGrid.addItem(spacerItem6, 0, 2, 1, 1)
        self.behaviorField = QtGui.QComboBox(self.centralwidget)
        self.behaviorField.setMinimumSize(QtCore.QSize(200, 0))
        self.behaviorField.setMaximumSize(QtCore.QSize(300, 16777215))
        self.behaviorField.setObjectName(_fromUtf8("behaviorField"))
        self.behaviorField.addItem(_fromUtf8(""))
        self.menuGrid.addWidget(self.behaviorField, 0, 4, 1, 1)
        self.startAllButton = QtGui.QPushButton(self.centralwidget)
        self.startAllButton.setObjectName(_fromUtf8("startAllButton"))
        self.menuGrid.addWidget(self.startAllButton, 0, 1, 1, 1)
        self.behaviorLabel = QtGui.QLabel(self.centralwidget)
        self.behaviorLabel.setMinimumSize(QtCore.QSize(70, 0))
        self.behaviorLabel.setMaximumSize(QtCore.QSize(80, 80))
        self.behaviorLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.behaviorLabel.setObjectName(_fromUtf8("behaviorLabel"))
        self.menuGrid.addWidget(self.behaviorLabel, 0, 3, 1, 1)
        self.mainGrid.addLayout(self.menuGrid, 4, 0, 1, 4)
        self.gridLayout.addLayout(self.mainGrid, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label_Box1_4.setText(_translate("MainWindow", "Box 1", None))
        self.birdEntryLabel_Box1_4.setText(_translate("MainWindow", "Bird", None))
        self.paramFileButton_Box1_4.setText(_translate("MainWindow", "...", None))
        self.checkActiveLabel_Box1_4.setText(_translate("MainWindow", "Active", None))
        self.paramFileLabel_Box1_4.setText(_translate("MainWindow", "File", None))
        self.stop_Box1_4.setText(_translate("MainWindow", "Stop", None))
        self.start_Box1_4.setText(_translate("MainWindow", "Start", None))
        self.birdEntryLabel_Box1.setText(_translate("MainWindow", "Bird", None))
        self.label_Box1.setText(_translate("MainWindow", "Box 1", None))
        self.checkActiveLabel_Box1.setText(_translate("MainWindow", "Active", None))
        self.paramFileLabel_Box1.setText(_translate("MainWindow", "File", None))
        self.statusText_Box1.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">3</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">4</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">5</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">6</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">7</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">8</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">9</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">10</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">11</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">12</p></body></html>", None))
        self.paramFileButton_Box1.setText(_translate("MainWindow", "...", None))
        self.stop_Box1.setText(_translate("MainWindow", "Stop", None))
        self.start_Box1.setText(_translate("MainWindow", "Start", None))
        self.stopAllButton.setText(_translate("MainWindow", "Stop All", None))
        self.behaviorField.setItemText(0, _translate("MainWindow", "GoNoGoInterruptExp", None))
        self.startAllButton.setText(_translate("MainWindow", "Start All", None))
        self.behaviorLabel.setText(_translate("MainWindow", "Behavior", None))

# import icons_rc
